"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { AlertCircle, CheckCircle2, Trophy } from "lucide-react";

// Tipe data berdasarkan Assessment Schema
export interface AssessmentReport {
  date: string;
  coachName: string;
  moduleTitle: string;
  level: string; // Beginner/Intermediate/Advance
  totalScore: number;
  scores: {
    biomechanics: number;
    footwork: number;
    strokeQuality: number;
    defense: number;
    offense: number;
    gameIQ: number;
    physique: number;
    [key: string]: number; // index signature for map
  };
  notes: string;
}

export default function CoachingReportCard({ report }: { report: AssessmentReport }) {
  // Helper untuk warna progress bar
  const getScoreColor = (score: number) => {
    if (score >= 5) return "bg-purple-600"; // Elite
    if (score >= 4) return "bg-green-600"; // Good
    if (score >= 3) return "bg-blue-500"; // Standard
    return "bg-orange-500"; // Needs Improvement
  };

  const getPercentage = (score: number) => (score / 5) * 100;

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header Rapor */}
      <div className="text-center space-y-2">
        <h1 className="text-2xl font-bold tracking-tight text-white">Coaching Report</h1>
        <p className="text-gray-400">{report.date} • {report.moduleTitle}</p>
      </div>

      {/* Summary Level */}
      <Card className="bg-[#121212] border-t-4 border-t-primary shadow-lg border-x-0 border-b-0">
        <CardContent className="pt-8 flex flex-col items-center text-center">
          <div className="w-20 h-20 bg-yellow-500/10 rounded-full flex items-center justify-center mb-4 border border-yellow-500/20 shadow-[0_0_15px_rgba(255,190,0,0.2)]">
            <Trophy className="w-10 h-10 text-yellow-500" />
          </div>
          <h2 className="text-xl font-bold text-white">Level Saat Ini</h2>
          <Badge className={`mt-3 text-lg px-6 py-1 rounded-full ${report.level === 'Advance (Elite)' ? 'bg-purple-600 hover:bg-purple-600' :
              report.level === 'Intermediate' ? 'bg-blue-600 hover:bg-blue-600' :
                'bg-green-600 hover:bg-green-600'
            }`}>
            {report.level}
          </Badge>
          <p className="mt-4 text-sm text-gray-400 max-w-sm">
            Total Skor: <span className="font-bold text-white text-lg">{report.totalScore}/35</span>
          </p>
        </CardContent>
      </Card>

      {/* Detail Penilaian */}
      <Card className="bg-[#121212] border-white/10">
        <CardHeader>
          <CardTitle className="text-white">Evaluasi Teknis</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {[
            { label: "Biomekanik (Grip & Wrist)", val: report.scores.biomechanics },
            { label: "Footwork (Gerak Kaki)", val: report.scores.footwork },
            { label: "Stroke Quality (Akurasi)", val: report.scores.strokeQuality },
            { label: "Defense (Pertahanan)", val: report.scores.defense },
            { label: "Offense (Serangan)", val: report.scores.offense },
            { label: "Game IQ (Taktik)", val: report.scores.gameIQ },
            { label: "Fisik & Mental", val: report.scores.physique },
          ].map((item, idx) => (
            <div key={idx} className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="font-medium text-gray-300">{item.label}</span>
                <span className="font-bold text-white">{item.val}/5</span>
              </div>
              <Progress value={getPercentage(item.val)} className="h-2 bg-white/10" indicatorClassName={getScoreColor(item.val)} />
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Feedback Coach */}
      <Card className="bg-[#1A1A1A] border-dashed border-white/20">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2 text-white">
            <AlertCircle className="w-4 h-4 text-primary" />
            Catatan Pelatih ({report.coachName})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm italic text-gray-300">
            "{report.notes || 'Tidak ada catatan khusus. Terus berlatih!'}"
          </p>
        </CardContent>
      </Card>

      <div className="text-center pt-4">
        <p className="text-[10px] text-gray-500 uppercase tracking-widest">Generated by Badmintour System</p>
      </div>
    </div>
  );
}
